CREATE DATABASE VOLS;

CREATE TABLE COMPANYIA(
	nomCO VARCHAR(30) PRIMARY KEY,
    websiteURL VARCHAR(30),
    cif VARCHAR(9) NOT NULL,
    pais VARCHAR(30) NOT NULL
);

ALTER TABLE companyia MODIFY websiteURL VARCHAR(128);

CREATE TABLE AEROPORT( 
    codiIATA VARCHAR(3) PRIMARY KEY, 
    nomAeroport VARCHAR(30) NOT NULL, 
    ciutat VARCHAR(30) NOT NULL, 
    pais VARCHAR(30) NOT NULL 
);

CREATE TABLE PASSATGER(
	id VARCHAR(9) PRIMARY KEY,
    tipudId VARCHAR(10) NOT NULL,
    nomPass VARCHAR(30) NOT NULL,
    cognoms VARCHAR(60) NOT NULL,
    email VARCHAR(256),
    dataNaixement VARCHAR(10) NOT NULL,
	sexe ENUM('home', 'dona', 'nodefinit') NOT NULL
);

ALTER TABLE passatger MODIFY dataNaixement DATE NOT NULL;

CREATE TABLE VOL(
	numVol INTEGER PRIMARY KEY,
    data VARCHAR(10) NOT NULL,
    capacitat INTEGER NOT NULL,
    nomCo VARCHAR(30) NOT NULL,
    codiIATAorigen VARCHAR(3) NOT NULL,
    codiIATAdesti VARCHAR(3) NOT NULL,
    CONSTRAINT fk_vol_companyia FOREIGN KEY (nomCo) REFERENCES COMPANYIA(nomCo),
    CONSTRAINT fk_vol_IATAorigen FOREIGN KEY (codiIATAorigen) REFERENCES AEROPORT(codiIATA),
    CONSTRAINT fk_vol_IATAdesti FOREIGN KEY (codiIATAdesti) REFERENCES AEROPORT(codiIATA)
);

CREATE TABLE RESERVA(
    numVol INTEGER NOT NULL,
    id VARCHAR(9) NOT NULL,
    data DATETIME NOT NULL,
    places INTEGER NOT NULL,
    CONSTRAINT fk_reserva_vol FOREIGN KEY (numVol) REFERENCES VOL(numVol),
    CONSTRAINT fk_reserva_passatger FOREIGN KEY (id) REFERENCES PASSATGER(id)
);

ALTER TABLE reserva ADD PRIMARY KEY(numVol, id);