CREATE DATABASE dept;

CREATE TABLE DEPT (
    nomDept VARCHAR(30) PRIMARY KEY
);

CREATE TABLE TREBALLADOR (
	id VARCHAR(9) PRIMARY KEY,
    tipusID VARCHAR(3) NOT NULL,
    nomT VARCHAR(32) NOT NULL,
    dept VARCHAR(30),
    CONSTRAINT fk_treballador_dept FOREIGN KEY (dept) REFERENCES DEPT(nomDept)
);