
package dev.jcasben.noticeboardclient2;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "NoticeBoardServiceImpl", targetNamespace = "http://noticeboardservice.jcasben.dev/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface NoticeBoardServiceImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteNotice", targetNamespace = "http://noticeboardservice.jcasben.dev/", className = "dev.jcasben.noticeboardclient2.DeleteNotice")
    @ResponseWrapper(localName = "deleteNoticeResponse", targetNamespace = "http://noticeboardservice.jcasben.dev/", className = "dev.jcasben.noticeboardclient2.DeleteNoticeResponse")
    @Action(input = "http://noticeboardservice.jcasben.dev/NoticeBoardServiceImpl/deleteNoticeRequest", output = "http://noticeboardservice.jcasben.dev/NoticeBoardServiceImpl/deleteNoticeResponse")
    public boolean deleteNotice(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<dev.jcasben.noticeboardclient2.Notice>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllNotices", targetNamespace = "http://noticeboardservice.jcasben.dev/", className = "dev.jcasben.noticeboardclient2.GetAllNotices")
    @ResponseWrapper(localName = "getAllNoticesResponse", targetNamespace = "http://noticeboardservice.jcasben.dev/", className = "dev.jcasben.noticeboardclient2.GetAllNoticesResponse")
    @Action(input = "http://noticeboardservice.jcasben.dev/NoticeBoardServiceImpl/getAllNoticesRequest", output = "http://noticeboardservice.jcasben.dev/NoticeBoardServiceImpl/getAllNoticesResponse")
    public List<Notice> getAllNotices();

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createNotice", targetNamespace = "http://noticeboardservice.jcasben.dev/", className = "dev.jcasben.noticeboardclient2.CreateNotice")
    @ResponseWrapper(localName = "createNoticeResponse", targetNamespace = "http://noticeboardservice.jcasben.dev/", className = "dev.jcasben.noticeboardclient2.CreateNoticeResponse")
    @Action(input = "http://noticeboardservice.jcasben.dev/NoticeBoardServiceImpl/createNoticeRequest", output = "http://noticeboardservice.jcasben.dev/NoticeBoardServiceImpl/createNoticeResponse")
    public String createNotice(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

}
