
package dev.jcasben.noticeboardclient2;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "noticeBoard", targetNamespace = "http://noticeboardservice.jcasben.dev/", wsdlLocation = "http://fedora:8080/notice-board-service-12077840037307675824.0-SNAPSHOT/noticeBoard?wsdl")
public class NoticeBoard
    extends Service
{

    private final static URL NOTICEBOARD_WSDL_LOCATION;
    private final static WebServiceException NOTICEBOARD_EXCEPTION;
    private final static QName NOTICEBOARD_QNAME = new QName("http://noticeboardservice.jcasben.dev/", "noticeBoard");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://fedora:8080/notice-board-service-12077840037307675824.0-SNAPSHOT/noticeBoard?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        NOTICEBOARD_WSDL_LOCATION = url;
        NOTICEBOARD_EXCEPTION = e;
    }

    public NoticeBoard() {
        super(__getWsdlLocation(), NOTICEBOARD_QNAME);
    }

    public NoticeBoard(WebServiceFeature... features) {
        super(__getWsdlLocation(), NOTICEBOARD_QNAME, features);
    }

    public NoticeBoard(URL wsdlLocation) {
        super(wsdlLocation, NOTICEBOARD_QNAME);
    }

    public NoticeBoard(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, NOTICEBOARD_QNAME, features);
    }

    public NoticeBoard(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NoticeBoard(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns NoticeBoardServiceImpl
     */
    @WebEndpoint(name = "NoticeBoardServiceImplPort")
    public NoticeBoardServiceImpl getNoticeBoardServiceImplPort() {
        return super.getPort(new QName("http://noticeboardservice.jcasben.dev/", "NoticeBoardServiceImplPort"), NoticeBoardServiceImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NoticeBoardServiceImpl
     */
    @WebEndpoint(name = "NoticeBoardServiceImplPort")
    public NoticeBoardServiceImpl getNoticeBoardServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://noticeboardservice.jcasben.dev/", "NoticeBoardServiceImplPort"), NoticeBoardServiceImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (NOTICEBOARD_EXCEPTION!= null) {
            throw NOTICEBOARD_EXCEPTION;
        }
        return NOTICEBOARD_WSDL_LOCATION;
    }

}
